name: DeNovoRefCorrect
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.9
  - bc=1.07.1
  - bcftools=1.16
  - bedtools=2.31.0
  - bioawk=1.0
  - bowtie2=2.5.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - coreutils=9.3
  - curl=8.1.2
  - expat=2.5.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freebayes=1.3.6
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=7.3.0
  - htslib=1.17
  - icu=72.1
  - k8=0.2.5
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.3
  - libgomp=13.1.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvm-openmp=8.0.1
  - minimap2=2.26
  - ncurses=6.4
  - nextflow=23.04.1
  - openjdk=20.0.0
  - openmp=8.0.1
  - openssl=3.1.1
  - parallel=20230522
  - pcre2=10.40
  - perl=5.32.1
  - pip=23.1.2
  - pixman=0.40.0
  - prinseq=0.20.4
  - pthread-stubs=0.4
  - python=3.10.11
  - python_abi=3.10
  - readline=8.2
  - samtools=1.17
  - setuptools=67.7.2
  - spades=3.15.5
  - sysroot_linux-64=2.17
  - tabixpp=1.1.0
  - tbb=2021.9.0
  - tk=8.6.12
  - trimmomatic=0.39
  - tzdata=2023c
  - vcflib=1.0.3
  - vcftools=0.1.16
  - wheel=0.40.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - biopython==1.81
    - numpy==1.25.0
    - pyvcf3==1.0.3
